"""initial schema

Revision ID: 8eea4a675b4d
Revises: 
Create Date: 2026-03-16 15:34:19.419353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eea4a675b4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sources_tags', sa.JSON(), nullable=True),
    sa.Column('raw_markdown', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_digests_published_at'), 'digests', ['published_at'], unique=False)
    op.create_table('source_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_status', sa.String(length=20), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_states_source_name'), 'source_states', ['source_name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('digest_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('relevance_score', sa.Integer(), nullable=True),
    sa.Column('why_relevant', sa.Text(), nullable=True),
    sa.Column('key_points', sa.JSON(), nullable=True),
    sa.Column('conversation_starters', sa.JSON(), nullable=True),
    sa.Column('original_url', sa.String(length=500), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['digest_id'], ['digests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_digest_id'), 'articles', ['digest_id'], unique=False)
    op.create_table('run_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('articles_found', sa.Integer(), nullable=True),
    sa.Column('digest_id', sa.Integer(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('log_output', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['digest_id'], ['digests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('run_logs')
    op.drop_index(op.f('ix_articles_digest_id'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_source_states_source_name'), table_name='source_states')
    op.drop_table('source_states')
    op.drop_index(op.f('ix_digests_published_at'), table_name='digests')
    op.drop_table('digests')
    # ### end Alembic commands ###
